### ISSUE TITLE
Layout keeps swapping off

### ISSUE THREAD

**Issue by payne911** [ergosteur/cf-keylayout#26]
I cannot select the layout as a permanent one : there is always the older Canadian keyboard input source which cannot be removed from the list of Input Sources.

Additionally, some applications don't seem to recognize the layout and thus keep automatically swapping back to the Canadian layout. That includes "Notes", for example.

*(macOS Big Sur v11.3.1)*

**Comment by joallard** [comment]
That seems annoying indeed. 

I do know that since basically, forever, if there's more than one version of the keylayout that has touched the system, several will seem to "hang" in the list of available ones. I also vaguely remember some spontaneous reversions (like you mention) when I developed the Brew formula.

I'm not sure there's much the code here can do directly, but I'll leave this open if there's any useful info gained or tips that can be used. Sorry this is happening to you!

**Comment by payne911** [comment]
Some potential leads:
* https://superuser.com/a/561613/1127689
* https://superuser.com/a/665726/1127689
* https://karabiner-elements.pqrs.org/docs/getting-started/features/
* https://matthieu.yiptong.ca/2009/09/09/canadian-french-keyboard-layout-for-mac-os-x/#comment-98359

Also, I had used your [`install`](https://github.com/ergosteur/cf-keylayout/blob/master/install) file: it installs the keyboard layout at the root of the machine, rather than at the user level. Is that on purpose? (The last point lead me to that, which also points to #17 )

**Comment by karimElmougi** [comment]
Just dropping by here to say it seems to be working fine on my M1 Mac running Big Sur v11.3.1.

**Comment by payne911** [comment]
After hours wasted, and and despite trying to log out and back in... it seems like a shut down was required for the thing to work properly.

Go figure.
