### ISSUE TITLE
How do you backtick?

### ISSUE THREAD

**Issue by abourget** [ergosteur/cf-keylayout#32]
I'm puzzled. On Linux, I was used to hitting the backtick action, then hitting space to insert just a backtick (without the space). Kind of a trigger to get just the character.  Now this doesn't work as expected. Hitting space after hitting the backtick character _adds_ the space. I tried using "backtick" + tab as a replacement, still much further away, but this doesn't work consistently in all apps, because some trigger things on Tab.

How do you guys make a backtick, when editing Markdown for example?

Maybe a small tweak to the layout could honor that "space" that turns a backtick into an actual backtick?

**Comment by abourget** [comment]
Ok, found that Shift+backtick would just add the backtick in directly. That solves it for me. Would have been awesome that it did support it, but that small adjustment is fine :) thanks for the layout!

**Comment by joallard** [comment]
Sorry you've been having unexpected trouble.

It's a bit weird because I just this week merged #30 allowing exactly that and this is now the expected behavior: backtick then space produces backtick only.

And yes, glad you found the workaround (this was one of my pet additions as a heavy Markdown user), Shift + modifier will usually yield it directly. (It works for `^` too)

Cheers!
